//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public Content()
        {
            this.ContentComments = new HashSet<ContentComment>();
            this.Posts = new HashSet<Post>();
            this.TagsToContents = new HashSet<TagsToContent>();
            this.Videos = new HashSet<Video>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Entry { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastModified { get; set; }
        public bool Visible { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<ContentComment> ContentComments { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<TagsToContent> TagsToContents { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
    }
}
