//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentComment
    {
        public ContentComment()
        {
            this.ContentComments1 = new HashSet<ContentComment>();
        }
    
        public int Id { get; set; }
        public string Comment { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ParentCommentId { get; set; }
        public int ContentId { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<ContentComment> ContentComments1 { get; set; }
        public virtual ContentComment ContentComment1 { get; set; }
        public virtual Content Content { get; set; }
    }
}
