//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlowCollectionEntities : DbContext
    {
        public FlowCollectionEntities()
            : base("name=FlowCollectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<PrivilegeLevel> PrivilegeLevels { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<TagsToPost> TagsToPosts { get; set; }
        public virtual DbSet<TagsToVideo> TagsToVideos { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
        public virtual DbSet<VideoComment> VideoComments { get; set; }
        public virtual DbSet<PostComment> PostComments { get; set; }
    }
}
