

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FlowRepository
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class FlowCollectionEntities : DbContext
{
    public FlowCollectionEntities()
        : base("name=FlowCollectionEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<PrivilegeLevel> PrivilegeLevels { get; set; }

    public virtual DbSet<Tag> Tags { get; set; }

    public virtual DbSet<UserVerification> UserVerifications { get; set; }

    public virtual DbSet<VerificationType> VerificationTypes { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<ContentComment> ContentComments { get; set; }

    public virtual DbSet<Post> Posts { get; set; }

    public virtual DbSet<TagsToContent> TagsToContents { get; set; }

    public virtual DbSet<Video> Videos { get; set; }

    public virtual DbSet<Content> Contents { get; set; }

    public virtual DbSet<Subscription> Subscriptions { get; set; }

    public virtual DbSet<SubscriptionType> SubscriptionTypes { get; set; }

    public virtual DbSet<Message> Messages { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

}

}

