//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostComment
    {
        public PostComment()
        {
            this.PostComment1 = new HashSet<PostComment>();
        }
    
        public int ID { get; set; }
        public string Comment { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> FK_UserID { get; set; }
        public Nullable<int> FK_ParentID { get; set; }
        public int FK_PostID { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual ICollection<PostComment> PostComment1 { get; set; }
        public virtual PostComment PostComment2 { get; set; }
        public virtual User User { get; set; }
    }
}
