//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagsToVideo
    {
        public int FK_TagID { get; set; }
        public int FK_VideoID { get; set; }
        public Nullable<bool> BS { get; set; }
    
        public virtual Tag Tag { get; set; }
        public virtual Video Video { get; set; }
    }
}
