//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Posts = new HashSet<Post>();
            this.PostComments = new HashSet<PostComment>();
            this.UserVerifications = new HashSet<UserVerification>();
            this.Videos = new HashSet<Video>();
            this.VideoComments = new HashSet<VideoComment>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string PasswordHash { get; set; }
        public string Email { get; set; }
        public int FK_PrivilegelevelID { get; set; }
        public System.DateTime Created { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<PostComment> PostComments { get; set; }
        public virtual PrivilegeLevel PrivilegeLevel { get; set; }
        public virtual ICollection<UserVerification> UserVerifications { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
        public virtual ICollection<VideoComment> VideoComments { get; set; }
    }
}
