
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FlowRepository
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public User()
    {

        this.UserVerifications = new HashSet<UserVerification>();

        this.ContentComments = new HashSet<ContentComment>();

        this.Contents = new HashSet<Content>();

        this.Subscriptions = new HashSet<Subscription>();

        this.Messages = new HashSet<Message>();

        this.Messages1 = new HashSet<Message>();

        this.Notifications = new HashSet<Notification>();

    }


    public int ID { get; set; }

    public string Username { get; set; }

    public string PasswordHash { get; set; }

    public string Email { get; set; }

    public int FK_PrivilegelevelID { get; set; }

    public System.DateTime Created { get; set; }

    public string ImageUrl { get; set; }



    public virtual PrivilegeLevel PrivilegeLevel { get; set; }

    public virtual ICollection<UserVerification> UserVerifications { get; set; }

    public virtual ICollection<ContentComment> ContentComments { get; set; }

    public virtual ICollection<Content> Contents { get; set; }

    public virtual ICollection<Subscription> Subscriptions { get; set; }

    public virtual ICollection<Message> Messages { get; set; }

    public virtual ICollection<Message> Messages1 { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; }

}

}
