//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVerification
    {
        public int ID { get; set; }
        public int FK_UserId { get; set; }
        public System.Guid VerifiedGuid { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int FK_VerficationId { get; set; }
        public bool isVerified { get; set; }
    
        public virtual VerificationType VerificationType { get; set; }
        public virtual User User { get; set; }
    }
}
