//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public Video()
        {
            this.TagsToVideos = new HashSet<TagsToVideo>();
            this.VideoComments = new HashSet<VideoComment>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime Created { get; set; }
        public string ThumbnailUrl { get; set; }
        public string VideoUrl { get; set; }
        public bool Visible { get; set; }
        public Nullable<int> FK_UserID { get; set; }
    
        public virtual ICollection<TagsToVideo> TagsToVideos { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<VideoComment> VideoComments { get; set; }
    }
}
