//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoComment
    {
        public VideoComment()
        {
            this.VideoComment1 = new HashSet<VideoComment>();
        }
    
        public int ID { get; set; }
        public string Comment { get; set; }
        public System.DateTime Created { get; set; }
        public int FK_VideoID { get; set; }
        public Nullable<int> FK_UserID { get; set; }
        public Nullable<int> FK_ParentID { get; set; }
    
        public virtual Video Video { get; set; }
        public virtual ICollection<VideoComment> VideoComment1 { get; set; }
        public virtual VideoComment VideoComment2 { get; set; }
        public virtual User User { get; set; }
    }
}
